apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quay
  title: Quay
  description: |
    This is the Quay.io component
  annotations:
    quay.io/repository-slug: rhdh-dast/origin-jenkins
