apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-dast
  title: RHDH-DAST
  description: |
    RHDH-DAST Components
  annotations:
    quay.io/repository-slug: rhdh-dast/origin-jenkins
