apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-dast-jenkins
  title: RHDH-DAST
  description: |
    RHDH-DAST Components
  annotations:
    quay.io/repository-slug: rhdh-dast/origin-jenkins
    github.com/project-slug: rhdh-dast/jenkins
spec:
  type: website
  system: rhdh-dast-jenkins
  owner: rhdh-dast-jenkins-authors
  lifecycle: production
  dependsOn:
    - resource:pgdb
    - resource:github
